# Generated by Django 5.1.7 on 2025-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия')),
                ('duration', models.PositiveIntegerField(verbose_name='Период действия (дней)')),
                ('device_uuid', models.UUIDField(blank=True, null=True, verbose_name='Идентификатор устройства')),
            ],
            options={
                'verbose_name': 'ключ',
                'verbose_name_plural': 'ключи',
            },
        ),
    ]
